name: moments_jcbn
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - attrs=25.3.0=pyh71513ae_0
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.1.31=hbcca054_0
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.3.2=py312h68727a3_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - dadi=2.4.0=py312h1a2ddb2_0
  - debugpy=1.8.14=py312h2ec8cdc_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - demes=0.2.3=pyhd8ed1ab_1
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - fonttools=4.57.0=py312h178313f_0
  - freetype=2.13.3=h48d6fc4_0
  - importlib-metadata=8.6.1=pyha770c72_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=9.1.0=pyhfb0248b_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.8=py312h84d6215_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=31_h59b9bed_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=31_he106b2a_openblas
  - libdeflate=1.23=h4ddbbb0_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libgomp=14.2.0=h767d61c_2
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - liblzma=5.8.1=hb9d3cd8_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libpng=1.6.47=h943b412_0
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.49.1=hee588c1_2
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libtiff=4.7.0=hd9ff511_3
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - matplotlib-base=3.10.1=py312hd3ec401_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - moments=1.3.1=py312hc9302aa_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nlopt=2.9.0=py312h1d0b465_0
  - numpy=1.26.4=py312heda63a1_0
  - openjpeg=2.5.3=h5fbd93e_0
  - openssl=3.5.0=h7b32b05_0
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py312hf9745cd_3
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.1.0=py312h80c1187_0
  - pip=25.0.1=pyh8b19718_0
  - platformdirs=4.3.7=pyh29332c3_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=7.0.0=py312h66e93f0_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - python=3.12.10=h9e4cc4f_0_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.12=6_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - pyzmq=26.4.0=py312hbf22597_0
  - qhull=2020.2=h434a139_5
  - readline=8.2=h8c095d6_2
  - ruamel.yaml=0.18.10=py312h66e93f0_0
  - ruamel.yaml.clib=0.2.8=py312h66e93f0_1
  - scipy=1.15.2=py312ha707e6e_0
  - setuptools=78.1.0=pyhff2d567_0
  - six=1.17.0=pyhd8ed1ab_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.13=noxft_h4845f30_101
  - tornado=6.4.2=py312h66e93f0_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.13.2=pyh29332c3_0
  - tzdata=2025b=h78e105d_0
  - unicodedata2=16.0.0=py312h66e93f0_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.21.0=pyhd8ed1ab_1
  - zstd=1.5.7=hb8e6e7a_2
prefix: /users/j/c/jcnunez/.conda/envs/moments_jcbn
